### ISSUE TITLE
Represents doesn't work with alias_attribute

### ISSUE THREAD

**Issue by andriusch** [toptal/granite#81]
```ruby
create_table "users", force: :cascade do |t|
  t.integer :sign_in_count
end

class User < ActiveRecord::Base
  alias_attribute :sign_ins, :sign_in_count
end

class DummyAction
  subject :user
  represents :sign_ins, of: :user
end
```

Since we use `represents` on aliased attribute, it doesn't correctly determine type and doesn't typecast the attribute correctly:

```ruby
action = DummyAction.new(user, sign_ins: '13')
action.sign_ins #=> "13"
```

**Comment by AlecksJohannes** [comment]
Hey @andriusch . I believe the Rails version 6.1 has fixed this issue https://blog.saeloun.com/2020/11/15/rails-6-1-allows-attribute-default-to-be-configured-but-keeping-its-type.html (which also works for alias_attribute)

But still I have an idea to fix for version <= 6.1
